language: node_js
node_js: node
sudo: required
services:
  - docker

script:
  - docker build -t priyeshs2/sample .

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-sample"
  env: "Docker"
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  bucket-name: "elasticbeanstalk-ap-south-1-980064312340"
  path: "docker-sample"
  on:
    branch: master
  skip_cleanup: true